name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Continuous Delivery"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH and Add EC2 to Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            cd /home/${USER}/your-backend-folder
            git pull origin main
            npm install
            pm2 restart backend || pm2 start index.js --name backend
          EOF
